---
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: Pass^w0rd_redis
    database: 1
    timeout: 3000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0