spring:
  profiles:
    active: local
    include: paydb-dev,redis-dev
  jackson:
    time-zone: GMT+8
    serialization:
      fail-on-empty-beans: false

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.rental.workflow.model
  #  typeEnumsPackage: com.rental.payment.beans.model.enums
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: UUID
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      #field-strategy: not_empty
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: mysql
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #驼峰下划线转换
    map-underscore-to-camel-case: true
    cache-enabled: false
